### ISSUE TITLE
About evaluation result.

### ISSUE THREAD

**Issue by ApolloRay** [zeyofu/BLINK_Benchmark#1]
Can you provide the original output ( before gpt3.5 ）for llava_v1.6_34b ？ For task multi-view_reasoning, I got prediction results which are almost (A).
![截屏2024-04-23 20 59 05](https://github.com/zeyofu/BLINK_Benchmark/assets/36093263/8dcd31e0-6be5-4d85-a819-c43d7ac6b216)

**Comment by ApolloRay** [comment]
![截屏2024-04-23 21 00 27](https://github.com/zeyofu/BLINK_Benchmark/assets/36093263/627637b8-8c08-4338-9242-4375ab504740)
For test visual_correspondence.

**Comment by zeyofu** [comment]
Hi, the "full prediction" means raw model output, and "prediction" means the output after choice extraction (GPT3.5)

**Comment by ApolloRay** [comment]
> Hi, the "full prediction" means raw model output, and "prediction" means the output after choice extraction (GPT3.5)

But I got totally different result. LLaVa offer a online demo, can you use the same prompt and the same concat image as input to get the same full prediction result ? Maybe you can offer three images and three prompts in this demo.

**Comment by zeyofu** [comment]
Hi it seems our settings are different. we use temperature=0 and locally ran llava1.6. Can you try this setting?

**Comment by ApolloRay** [comment]
![截屏2024-05-06 14 58 48](https://github.com/zeyofu/BLINK_Benchmark/assets/36093263/627c6b24-0ebc-4494-bdd1-f44d7d54ddb0)
Test difference.

**Comment by ApolloRay** [comment]
In saved output, llava v1.5 13b，full prediction gave full sentences. But in llava v1.6 34b, full predictions were just A/B/C/D ？
