### ISSUE TITLE
Feeding more than one image to LLaVA

### ISSUE THREAD

**Issue by SaraGhazanfari** [zeyofu/BLINK_Benchmark#10]
Hi,

Thanks for the nice work!
How do you feed 3 images to LLaVA for the visual similarity task?

Thanks,
Sara

**Comment by zeyofu** [comment]
Hi Sara, 

Thanks for your interest! 
For models that only took single image inputs such as LLaVA, we concatenated all the images together to feed as input. Details can be found in Section 4.1 and Appendix C.2
