### ISSUE TITLE
The Absence of Test Set Ground Truth

### ISSUE THREAD

**Issue by mao1207** [zeyofu/BLINK_Benchmark#12]
It seems that you haven't released the ground truth for the test set, and it's also marked as "hidden" on Hugging Face. Do you have any plans to release the ground truth?

**Comment by mao1207** [comment]
Sorry, I just realized that you might be concerned about the test set data being leaked. No worries, I'll submit my results on your evaluation website. And this is really a good job!

**Comment by zeyofu** [comment]
Thanks so much for your interest! I just approved all your submissions :D
