### ISSUE TITLE
Test difference.

### ISSUE THREAD

**Issue by ApolloRay** [zeyofu/BLINK_Benchmark#2]
![截屏2024-05-06 14 58 48](https://github.com/zeyofu/BLINK_Benchmark/assets/36093263/2e894224-0227-45d5-95d9-f9a1f084600d)

**Comment by ApolloRay** [comment]
For the multi-view reasoning task, the prediction results of model llava-1.6 are all (A).

**Comment by ApolloRay** [comment]
![image](https://github.com/zeyofu/BLINK_Benchmark/assets/36093263/35c44e2c-d2fa-4e94-b998-0e0ec423a3b1)

**Comment by ApolloRay** [comment]
Test in official demo (LLaVa-1.6-34B)

**Comment by zeyofu** [comment]
Hi ApolloRay, apologies for the late reply! Feel free to shoot me an email at xingyuf2@seas.upenn.edu, and I'm happy to schedule a meeting and discuss about this issue with you.
