### ISSUE TITLE
prediction can not extract answer from full_prediction

### ISSUE THREAD

**Issue by Liuziyu77** [zeyofu/BLINK_Benchmark#7]
![image](https://github.com/user-attachments/assets/e1fa0941-d4f5-46de-9012-4a338746c31a)
why prediction can not extract 'A' from full_prediction? the whole ``.json`` file all face such problem.

**Comment by zeyofu** [comment]
Could you kindly point me to the file please?

**Comment by Liuziyu77** [comment]
Problem solved. Thank you very much



---Original---
From: "Xingyu ***@***.***&gt;
Date: Mon, Jul 15, 2024 22:17 PM
To: ***@***.***&gt;;
Cc: "Ziyu ***@***.******@***.***&gt;;
Subject: Re: [zeyofu/BLINK_Benchmark] prediction can not extract answer fromfull_prediction (Issue #7)




 
Could you kindly point me to the file please?

**Comment by zeyofu** [comment]
Glad to hear that!
