### ISSUE TITLE
reproduce llava's results

### ISSUE THREAD

**Issue by Liuziyu77** [zeyofu/BLINK_Benchmark#8]
When I tested with llava-v1.5-7b, full_prediction took longer than the test results you gave, and the extraction from full_prediction to prediction often went wrong. Can you give me some parameter settings for llava-v1.5-7B inference, or the code you used to test llava-v1.5-7B?

**Comment by zeyofu** [comment]
Hi, we just used https://github.com/open-compass/VLMEvalKit/tree/main for the model, setting the temperature to be 0.0. 

I'll check on the extraction.

**Comment by zeyofu** [comment]
Closing because no more new conversation
