### ISSUE TITLE
Why is the annotation method of the cases given in your paper different from the actual one provided in huggingface?

### ISSUE THREAD

**Issue by Anonymous3790** [zeyofu/BLINK_Benchmark#9]
Why is the annotation method of the cases given in your paper different from the actual one provided in huggingface?

in your paper
![image](https://github.com/user-attachments/assets/c1ee56a1-f551-4ad1-b18d-5d7f3d6d4a2a)

in huggingface: 

![image](https://github.com/user-attachments/assets/cd20c88b-dc95-4b0e-ad0f-b7234fc6d9a6)

**Comment by zeyofu** [comment]
Hi, Thanks for asking. As in Figure 5 caption and Figure 1 caption, the markers (visual prompts) in the figures in our paper are intentionally enlarged and different from the actual ones for illustration purposes. The correct annotations are as in the huggingface dataset.
